const ASK_WIDGET_THEME = '<style id="mell-ask-theme">.brand small{margin-top:.16rem!important;color:#a9b9ce;font-size:.66rem;line-height:1.15;letter-spacing:.105em}.hero .actions>a{display:none}.button.ghost.mell-ask-inline-trigger{position:relative;min-height:48px;padding:0 1.35rem;border:2px solid rgba(34,211,238,.88);border-radius:999px;background:linear-gradient(180deg,rgba(2,17,31,.92),rgba(7,17,31,.86));color:#67e8f9;font-size:1rem;font-weight:860;letter-spacing:0;text-shadow:0 0 14px rgba(34,211,238,.42);box-shadow:0 0 0 1px rgba(56,189,248,.18),0 0 24px rgba(34,211,238,.26),0 16px 38px rgba(0,0,0,.3),inset 0 1px 0 rgba(255,255,255,.08);transition:transform 180ms ease,border-color 180ms ease,box-shadow 180ms ease,background 180ms ease,color 180ms ease}.button.ghost.mell-ask-inline-trigger::before{content:none}.button.ghost.mell-ask-inline-trigger:hover{transform:translateY(-4px);border-color:#67e8f9;background:linear-gradient(180deg,rgba(3,30,48,.94),rgba(6,21,36,.9));color:#ecfeff;box-shadow:0 0 0 1px rgba(125,211,252,.42),0 0 34px rgba(34,211,238,.42),0 22px 52px rgba(0,0,0,.4),inset 0 1px 0 rgba(255,255,255,.12)}.button.ghost.mell-ask-inline-trigger:focus-visible{outline:3px solid rgba(125,211,252,.9);outline-offset:4px}</style>';
const DEMO_FLOW_THEME = '<style id="mell-demo-flow-theme">.demo-step{position:relative;z-index:0;overflow:visible;transition:transform 180ms ease,border-color 180ms ease,box-shadow 180ms ease,background 180ms ease}.demo-step:hover,.demo-step:focus-within{z-index:2;transform:translateY(-4px);border-color:rgba(125,211,252,.52);background:linear-gradient(180deg,rgba(16,31,53,.96),rgba(9,18,33,.86));box-shadow:0 18px 46px rgba(0,0,0,.34),0 0 0 1px rgba(34,211,238,.16)}.demo-step:not(:last-child)::after{content:"→";position:absolute;right:-1.04rem;top:50%;display:grid;width:1.7rem;height:1.7rem;place-items:center;border:1px solid rgba(125,211,252,.34);border-radius:999px;background:rgba(4,9,20,.92);color:#7dd3fc;font-size:1rem;font-weight:900;line-height:1;opacity:0;transform:translate(-.45rem,-50%);box-shadow:0 0 18px rgba(34,211,238,.2);pointer-events:none;transition:opacity 180ms ease,transform 180ms ease,border-color 180ms ease}.demo-step:hover:not(:last-child)::after,.demo-step:focus-within:not(:last-child)::after{opacity:1;transform:translate(0,-50%);border-color:rgba(125,211,252,.62)}@media(max-width:980px){.demo-step:not(:last-child)::after{right:50%;top:auto;bottom:-1.1rem;transform:translate(50%,-.45rem);content:"↓"}.demo-step:hover:not(:last-child)::after,.demo-step:focus-within:not(:last-child)::after{transform:translate(50%,0)}}@media(prefers-reduced-motion:reduce){.demo-step,.demo-step::after{transition:none!important}.demo-step:hover,.demo-step:focus-within{transform:none}}</style>';
const PROCESS_FLOW_THEME = '<style id="mell-process-flow-theme">.flow-step{position:relative;z-index:0;overflow:visible;transition:transform 180ms ease,border-color 180ms ease,box-shadow 180ms ease,background 180ms ease}.flow-step:hover,.flow-step:focus-within{z-index:2;transform:translateY(-4px);border-color:rgba(125,211,252,.52);background:linear-gradient(180deg,rgba(16,31,53,.96),rgba(9,18,33,.86));box-shadow:0 18px 46px rgba(0,0,0,.34),0 0 0 1px rgba(34,211,238,.16)}.flow-step:not(:last-child)::after{content:"→";position:absolute;right:-.98rem;top:50%;display:grid;width:1.7rem;height:1.7rem;place-items:center;border:1px solid rgba(125,211,252,.34);border-radius:999px;background:rgba(4,9,20,.92);color:#7dd3fc;font-size:1rem;font-weight:900;line-height:1;opacity:0;transform:translate(-.45rem,-50%);box-shadow:0 0 18px rgba(34,211,238,.2);pointer-events:none;transition:opacity 180ms ease,transform 180ms ease,border-color 180ms ease}.flow-step:hover:not(:last-child)::after,.flow-step:focus-within:not(:last-child)::after{opacity:1;transform:translate(0,-50%);border-color:rgba(125,211,252,.62)}@media(max-width:980px){.flow-step:not(:last-child)::after{right:50%;top:auto;bottom:-1.1rem;transform:translate(50%,-.45rem);content:"↓"}.flow-step:hover:not(:last-child)::after,.flow-step:focus-within:not(:last-child)::after{transform:translate(50%,0)}}@media(prefers-reduced-motion:reduce){.flow-step,.flow-step::after{transition:none!important}.flow-step:hover,.flow-step:focus-within{transform:none}}</style>';
const ASK_WIDGET_LABEL_SCRIPT = '<script>(function(){function applyMeLLLabels(){var brand=document.querySelector(".brand small");if(brand){brand.textContent="Governança Cognitiva Corporativa";}var label="MeLL IA Assist";document.querySelectorAll(".mell-ask-inline-trigger").forEach(function(button){button.textContent=label;button.setAttribute("aria-label",label+" - chat de atendimento");});document.querySelectorAll(".mell-ask-launcher").forEach(function(button){var text=button.querySelector("span:last-child");if(text){text.textContent=label;}button.setAttribute("aria-label",label+" - chat de atendimento");});document.querySelectorAll(".mell-ask-message").forEach(function(message){message.textContent=message.textContent.replace("Sou o ASK de atendimento da MeLL.","Sou o MeLL IA Assist, chat de atendimento da MeLL.").replace("Sou o chat de atendimento MeLL AI.","Sou o MeLL IA Assist, chat de atendimento da MeLL.").replace("Origem: ASK de atendimento do site","Origem: MeLL IA Assist do site").replace("Origem: Chat de atendimento MeLL AI do site","Origem: MeLL IA Assist do site");});}if(document.readyState==="loading"){window.addEventListener("DOMContentLoaded",applyMeLLLabels);}else{applyMeLLLabels();}})();</script>';
const ASK_WIDGET_SNIPPET = ASK_WIDGET_THEME + DEMO_FLOW_THEME + PROCESS_FLOW_THEME + '<script src="/mell-atendimento-widget.js?v=20260525-process-flow-hover-arrows" defer></script>' + ASK_WIDGET_LABEL_SCRIPT;

export async function onRequest(context) {
  const response = await context.next();
  const contentType = response.headers.get("content-type") || "";

  if (!contentType.includes("text/html")) {
    return response;
  }

  return new HTMLRewriter()
    .on("body", {
      element(element) {
        element.append(ASK_WIDGET_SNIPPET, { html: true });
      },
    })
    .transform(response);
}
